# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
    identifier = "mail"
    name       = "Mail"
    url        = "mailto:support@rumosky.com"

    [social.params]
        icon = "mail"

[[social]]
    identifier = "qq"
    name       = "QQ"
    url        = "mailto:774026486@qq.com"

    [social.params]
        icon = "brand-qq"

[[social]]
    identifier = "github"
    name       = "Github"
    url        = "https://github.com/rumosky"

    [social.params]
        icon = "brand-github"
