# Pages placed under these sections will be shown on homepage and archive page.
mainSections = ["post"]
# Output page's full content in RSS.
rssFullContent = true
favicon        = "img/favicon.ico"

# Accepted values: "default", "lastmod"
# default = see https://gohugo.io/quick-reference/glossary/#default-sort-order
# lastmod = sort by last modified date, in descending order
SortBy              = "default"

[footer]
    since      = 2018
    customText = ""

[dateFormat]
    published   = ":date_full"
    lastUpdated = ":date_full"

[sidebar]
    emoji    = ""
    subtitle = "一个假理科生&伪程序员"
    avatar   = "img/avatar.jpg"

[widgets]
    homepage = [
        { type = "search" },
        { type = "archives", params = { limit = 5 } },
        { type = "categories", params = { limit = 4 } },
        { type = "tag-cloud", params = { limit = 10 } },
    ]
    page = [{ type = "toc" }]

[article]
    headingAnchor = false
    math          = true
    readingTime   = true

    [article.license]
        enabled = false
        default = "Licensed under CC BY-NC-SA 4.0"

[opengraph.twitter]
    site = ""
    card = "summary_large_image"

[colorScheme]
    toggle  = true
    default = "auto"

[imageProcessing]
    autoOrient = false

    [imageProcessing.external]
        timeout = "5s"

    [imageProcessing.content]
        widths  = [800, 1600, 2400]
        enabled = true

    [imageProcessing.thumbnail]
        enabled = true

## Comments
[comments]
    enabled  = false
    provider = "disqus"

    # See all the available configurations at https://github.com/CaiJimmy/hugo-theme-stack/blob/master/config/_default/params.toml
    # Copy the configurations you need from there and paste it here.
